//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MityaginaNP.UX.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document(Guid fileId, string fileName, byte[] fileData, string project, int task)
        {
            FileId = fileId;
            FileName = fileName;
            FileData = fileData;
            Project1 = project;
            Task = task;
        }

        public Document()
        {

        }

        public System.Guid DocumentID { get; set; }
        public byte[] DocumentSource { get; set; }
        public string ProjectID { get; set; }
        public string DocumentName { get; set; }
        public Nullable<int> TaskID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual TaskProject TaskProject { get; set; }
        public Guid FileId { get; }
        public string FileName { get; }
        public byte[] FileData { get; }
        public string Project1 { get; }
        public int Task { get; }
    }
}
