//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MityaginaNP.UX.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        private Guid fileId;
        private string fileName;
        private byte[] fileData;
        private string project;
        private int task;

        public Document()
        {

        }

        public Document(Guid fileId, string fileName, byte[] fileData, string project, int task)
        {
            this.fileId = DocumentID;
            this.fileName = DocumentName;
            this.fileData = DocumentSource;
            this.project = ProjectID;
            this.task = TaskID;
        }

        public System.Guid DocumentID { get; set; }
        public byte[] DocumentSource { get; set; }
        public string ProjectID { get; set; }
        public string DocumentName { get; set; }
        public int TaskID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual TaskProject TaskProject { get; set; }
    }
}
