//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MityaginaNP.UX.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSample
    {
        public FileSample(Guid fileId, string fileName, byte[] fileData)
        {
            FileId = fileId;
            FileName = fileName;
            FileData = fileData;
        }
        public FileSample()
        {
            
        }

        public System.Guid FileId { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
    }
}
