//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MityaginaNP.UX.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public int TypeID { get; set; }
        public string UserLogin { get; set; }
        public System.DateTime NotificationDateTime { get; set; }
        public Nullable<int> TaskID { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
        public virtual User User { get; set; }
        public virtual TaskProject TaskProject { get; set; }
    }
}
